export { renderPlainTextPdf } from '@/pdf/text-page-renderer';
export type { TextRenderOptions, FontInput } from '@/pdf/text-page-renderer';
export { renderStyledPdf } from '@/pdf/styled-page-renderer';
export type { DocumentInfo, StyledRenderOptions, PdfALevel } from '@/pdf/styled-page-renderer';
export { signPdf } from '@/pdf/signature';
export type { SignaturePlaceholder, SignerCredentials, SignatureOptions } from '@/pdf/signature';
export type { AttachedFile, AFRelationship } from '@/pdf/embedded-file';
export { embedTtfFont } from '@/pdf/cid-font';
export type { EmbeddedFont } from '@/pdf/cid-font';
export { embedImage, detectImageFormat } from '@/pdf/image-xobject';
export type { EmbeddedImage, ImageFormat } from '@/pdf/image-xobject';
