// Generate the Markdown API reference from the public TypeScript surface and its
// TSDoc comments, via @tanstack/config/typedoc (TypeDoc + typedoc-plugin-markdown
// + frontmatter). Output lands in docs/reference/ and is fully regenerable — each
// page carries a "DO NOT EDIT: autogenerated" banner, so never hand-edit it.
//
//   npm run docs:api
//
// The two entry points mirror the package `exports`: the root API and the typed
// `reamkit/document-model` subpath.

import { generateReferenceDocs } from '@tanstack/config/typedoc';

async function main(): Promise<void> {
  await generateReferenceDocs({
    packages: [
      {
        name: 'reamkit',
        entryPoints: ['./src/index.ts', './src/document-model/index.ts'],
        tsconfig: './tsconfig.json',
        outputDir: './docs/reference',
      },
    ],
    gitBranch: 'main',
  });
  console.log('API reference written to docs/reference/');
}

void main();
