// §18.8.40 — the table styles Excel has built in, which a workbook names in
// `<tableStyleInfo name>` and never writes down: TableStyleLight1…21,
// TableStyleMedium1…28 and TableStyleDark1…11. Generated from the standard's
// own definitions — ECMA-376 Part 1, the electronic insert
// OfficeOpenXML-SpreadsheetMLStyles.zip, presetTableStyles.xml (whose dxfIds,
// unlike a workbook's, count from one). A colour is a theme slot — 0 lt1, 1
// dk1, 2 lt2, 3 dk2, 4…9 accent1…6 — and the tint applied to it.

import type { TableStyleElementType } from '@/core/spreadsheet-model';

/** A theme colour: its slot and the tint applied to it (0 = none). */
export type PresetColor = readonly [theme: number, tint: number];

/** One line of a preset: its style and colour. */
export type PresetEdge = readonly ['thin' | 'medium' | 'thick' | 'double', PresetColor];

/** A preset's differential format: what one region of a table takes. */
export interface PresetDxf {
  readonly bold?: boolean;
  readonly color?: PresetColor;
  readonly fill?: PresetColor;
  readonly border?: {
    readonly left?: PresetEdge;
    readonly right?: PresetEdge;
    readonly top?: PresetEdge;
    readonly bottom?: PresetEdge;
    readonly vertical?: PresetEdge;
    readonly horizontal?: PresetEdge;
  };
}

// prettier-ignore
const DXFS: ReadonlyArray<PresetDxf> = [
  { color: [1, 0.0], fill: [9, 0.8], border: { left: ['thin', [9, 0.4]], right: ['thin', [9, 0.4]], top: ['thin', [9, 0.4]], bottom: ['thin', [9, 0.4]], vertical: ['thin', [9, 0.4]], horizontal: ['thin', [9, 0.4]] } },
  { bold: true, color: [1, 0.0] },
  { bold: true, color: [1, 0.0], border: { top: ['medium', [9, 0.0]] } },
  { fill: [9, 0.6] },
  { color: [1, 0.0], fill: [8, 0.8], border: { left: ['thin', [8, 0.4]], right: ['thin', [8, 0.4]], top: ['thin', [8, 0.4]], bottom: ['thin', [8, 0.4]], vertical: ['thin', [8, 0.4]], horizontal: ['thin', [8, 0.4]] } },
  { bold: true, color: [1, 0.0], border: { top: ['medium', [8, 0.0]] } },
  { fill: [8, 0.6] },
  { color: [1, 0.0], fill: [7, 0.8], border: { left: ['thin', [7, 0.4]], right: ['thin', [7, 0.4]], top: ['thin', [7, 0.4]], bottom: ['thin', [7, 0.4]], vertical: ['thin', [7, 0.4]], horizontal: ['thin', [7, 0.4]] } },
  { bold: true, color: [1, 0.0], border: { top: ['medium', [7, 0.0]] } },
  { fill: [7, 0.6] },
  { color: [1, 0.0], fill: [6, 0.8], border: { left: ['thin', [6, 0.4]], right: ['thin', [6, 0.4]], top: ['thin', [6, 0.4]], bottom: ['thin', [6, 0.4]], vertical: ['thin', [6, 0.4]], horizontal: ['thin', [6, 0.4]] } },
  { bold: true, color: [1, 0.0], border: { top: ['medium', [6, 0.0]] } },
  { fill: [6, 0.6] },
  { color: [1, 0.0], fill: [5, 0.8], border: { left: ['thin', [5, 0.4]], right: ['thin', [5, 0.4]], top: ['thin', [5, 0.4]], bottom: ['thin', [5, 0.4]], vertical: ['thin', [5, 0.4]], horizontal: ['thin', [5, 0.4]] } },
  { bold: true, color: [1, 0.0], border: { top: ['medium', [5, 0.0]] } },
  { fill: [5, 0.6] },
  { color: [1, 0.0], fill: [4, 0.8], border: { left: ['thin', [4, 0.4]], right: ['thin', [4, 0.4]], top: ['thin', [4, 0.4]], bottom: ['thin', [4, 0.4]], vertical: ['thin', [4, 0.4]], horizontal: ['thin', [4, 0.4]] } },
  { bold: true, color: [1, 0.0], border: { top: ['medium', [4, 0.0]] } },
  { fill: [4, 0.6] },
  { color: [1, 0.0], fill: [0, -0.15], border: { left: ['thin', [1, 0.0]], right: ['thin', [1, 0.0]], top: ['thin', [1, 0.0]], bottom: ['thin', [1, 0.0]], vertical: ['thin', [1, 0.0]], horizontal: ['thin', [1, 0.0]] } },
  { bold: true, color: [1, 0.0], border: { top: ['medium', [1, 0.0]] } },
  { fill: [0, -0.35] },
  { color: [1, 0.0], border: { top: ['medium', [1, 0.0]], bottom: ['medium', [1, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [9, 0.0], border: { bottom: ['medium', [1, 0.0]] } },
  { border: { top: ['double', [1, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [9, 0.0] },
  { fill: [0, -0.15] },
  { bold: true, color: [0, 0.0], fill: [8, 0.0], border: { bottom: ['medium', [1, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [8, 0.0] },
  { bold: true, color: [0, 0.0], fill: [7, 0.0], border: { bottom: ['medium', [1, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [7, 0.0] },
  { bold: true, color: [0, 0.0], fill: [6, 0.0], border: { bottom: ['medium', [1, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [6, 0.0] },
  { bold: true, color: [0, 0.0], fill: [5, 0.0], border: { bottom: ['medium', [1, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [5, 0.0] },
  { bold: true, color: [0, 0.0], fill: [4, 0.0], border: { bottom: ['medium', [1, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [4, 0.0] },
  { color: [1, 0.0], border: { left: ['thin', [1, 0.0]], right: ['thin', [1, 0.0]], top: ['medium', [1, 0.0]], bottom: ['medium', [1, 0.0]], vertical: ['thin', [1, 0.0]], horizontal: ['thin', [1, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [1, 0.0], border: { bottom: ['medium', [1, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [1, 0.0] },
  { color: [1, 0.0], fill: [9, 0.8], border: { vertical: ['thin', [0, 0.0]], horizontal: ['thin', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [9, 0.0], border: { bottom: ['thick', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [9, 0.0], border: { top: ['thick', [0, 0.0]] } },
  { color: [1, 0.0], fill: [8, 0.8], border: { vertical: ['thin', [0, 0.0]], horizontal: ['thin', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [8, 0.0], border: { bottom: ['thick', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [8, 0.0], border: { top: ['thick', [0, 0.0]] } },
  { color: [1, 0.0], fill: [7, 0.8], border: { vertical: ['thin', [0, 0.0]], horizontal: ['thin', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [7, 0.0], border: { bottom: ['thick', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [7, 0.0], border: { top: ['thick', [0, 0.0]] } },
  { color: [1, 0.0], fill: [6, 0.8], border: { vertical: ['thin', [0, 0.0]], horizontal: ['thin', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [6, 0.0], border: { bottom: ['thick', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [6, 0.0], border: { top: ['thick', [0, 0.0]] } },
  { color: [1, 0.0], fill: [5, 0.8], border: { vertical: ['thin', [0, 0.0]], horizontal: ['thin', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [5, 0.0], border: { bottom: ['thick', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [5, 0.0], border: { top: ['thick', [0, 0.0]] } },
  { color: [1, 0.0], fill: [4, 0.8], border: { vertical: ['thin', [0, 0.0]], horizontal: ['thin', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [4, 0.0], border: { bottom: ['thick', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [4, 0.0], border: { top: ['thick', [0, 0.0]] } },
  { color: [1, 0.0], fill: [0, -0.15], border: { vertical: ['thin', [0, 0.0]], horizontal: ['thin', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [1, 0.0], border: { bottom: ['thick', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [1, 0.0], border: { top: ['thick', [0, 0.0]] } },
  { color: [1, 0.0], border: { left: ['thin', [9, 0.4]], right: ['thin', [9, 0.4]], top: ['thin', [9, 0.4]], bottom: ['thin', [9, 0.4]], horizontal: ['thin', [9, 0.4]] } },
  { bold: true, color: [1, 0.0], border: { top: ['double', [9, 0.0]] } },
  { fill: [9, 0.8] },
  { color: [1, 0.0], border: { left: ['thin', [8, 0.4]], right: ['thin', [8, 0.4]], top: ['thin', [8, 0.4]], bottom: ['thin', [8, 0.4]], horizontal: ['thin', [8, 0.4]] } },
  { bold: true, color: [1, 0.0], border: { top: ['double', [8, 0.0]] } },
  { fill: [8, 0.8] },
  { color: [1, 0.0], border: { left: ['thin', [7, 0.4]], right: ['thin', [7, 0.4]], top: ['thin', [7, 0.4]], bottom: ['thin', [7, 0.4]], horizontal: ['thin', [7, 0.4]] } },
  { bold: true, color: [1, 0.0], border: { top: ['double', [7, 0.0]] } },
  { fill: [7, 0.8] },
  { color: [1, 0.0], border: { left: ['thin', [6, 0.4]], right: ['thin', [6, 0.4]], top: ['thin', [6, 0.4]], bottom: ['thin', [6, 0.4]], horizontal: ['thin', [6, 0.4]] } },
  { bold: true, color: [1, 0.0], border: { top: ['double', [6, 0.0]] } },
  { fill: [6, 0.8] },
  { color: [1, 0.0], border: { left: ['thin', [5, 0.4]], right: ['thin', [5, 0.4]], top: ['thin', [5, 0.4]], bottom: ['thin', [5, 0.4]], horizontal: ['thin', [5, 0.4]] } },
  { bold: true, color: [1, 0.0], border: { top: ['double', [5, 0.0]] } },
  { fill: [5, 0.8] },
  { color: [1, 0.0], border: { left: ['thin', [4, 0.4]], right: ['thin', [4, 0.4]], top: ['thin', [4, 0.4]], bottom: ['thin', [4, 0.4]], horizontal: ['thin', [4, 0.4]] } },
  { bold: true, color: [1, 0.0], border: { top: ['double', [4, 0.0]] } },
  { fill: [4, 0.8] },
  { color: [1, 0.0], border: { left: ['thin', [1, 0.0]], right: ['thin', [1, 0.0]], top: ['thin', [1, 0.0]], bottom: ['thin', [1, 0.0]], horizontal: ['thin', [1, 0.0]] } },
  { bold: true, color: [1, 0.0], border: { top: ['double', [1, 0.0]] } },
  { color: [1, 0.0], border: { left: ['thin', [9, 0.0]], right: ['thin', [9, 0.0]], top: ['thin', [9, 0.0]], bottom: ['thin', [9, 0.0]], vertical: ['thin', [9, 0.0]], horizontal: ['thin', [9, 0.0]] } },
  { bold: true, color: [1, 0.0], border: { bottom: ['medium', [9, 0.0]] } },
  { color: [1, 0.0], border: { left: ['thin', [8, 0.0]], right: ['thin', [8, 0.0]], top: ['thin', [8, 0.0]], bottom: ['thin', [8, 0.0]], vertical: ['thin', [8, 0.0]], horizontal: ['thin', [8, 0.0]] } },
  { bold: true, color: [1, 0.0], border: { bottom: ['medium', [8, 0.0]] } },
  { color: [1, 0.0], border: { left: ['thin', [7, 0.0]], right: ['thin', [7, 0.0]], top: ['thin', [7, 0.0]], bottom: ['thin', [7, 0.0]], vertical: ['thin', [7, 0.0]], horizontal: ['thin', [7, 0.0]] } },
  { bold: true, color: [1, 0.0], border: { bottom: ['medium', [7, 0.0]] } },
  { color: [1, 0.0], border: { left: ['thin', [6, 0.0]], right: ['thin', [6, 0.0]], top: ['thin', [6, 0.0]], bottom: ['thin', [6, 0.0]], vertical: ['thin', [6, 0.0]], horizontal: ['thin', [6, 0.0]] } },
  { bold: true, color: [1, 0.0], border: { bottom: ['medium', [6, 0.0]] } },
  { color: [1, 0.0], border: { left: ['thin', [5, 0.0]], right: ['thin', [5, 0.0]], top: ['thin', [5, 0.0]], bottom: ['thin', [5, 0.0]], vertical: ['thin', [5, 0.0]], horizontal: ['thin', [5, 0.0]] } },
  { bold: true, color: [1, 0.0], border: { bottom: ['medium', [5, 0.0]] } },
  { color: [1, 0.0], border: { left: ['thin', [4, 0.0]], right: ['thin', [4, 0.0]], top: ['thin', [4, 0.0]], bottom: ['thin', [4, 0.0]], vertical: ['thin', [4, 0.0]], horizontal: ['thin', [4, 0.0]] } },
  { bold: true, color: [1, 0.0], border: { bottom: ['medium', [4, 0.0]] } },
  { color: [1, 0.0], border: { left: ['thin', [1, 0.0]], right: ['thin', [1, 0.0]], top: ['thin', [1, 0.0]], bottom: ['thin', [1, 0.0]], vertical: ['thin', [1, 0.0]], horizontal: ['thin', [1, 0.0]] } },
  { bold: true, color: [1, 0.0], border: { bottom: ['medium', [1, 0.0]] } },
  { color: [1, 0.0], border: { left: ['thin', [9, 0.0]], right: ['thin', [9, 0.0]], top: ['thin', [9, 0.0]], bottom: ['thin', [9, 0.0]] } },
  { border: { top: ['thin', [9, 0.0]] } },
  { border: { left: ['thin', [9, 0.0]] } },
  { color: [1, 0.0], border: { left: ['thin', [8, 0.0]], right: ['thin', [8, 0.0]], top: ['thin', [8, 0.0]], bottom: ['thin', [8, 0.0]] } },
  { border: { top: ['thin', [8, 0.0]] } },
  { border: { left: ['thin', [8, 0.0]] } },
  { color: [1, 0.0], border: { left: ['thin', [7, 0.0]], right: ['thin', [7, 0.0]], top: ['thin', [7, 0.0]], bottom: ['thin', [7, 0.0]] } },
  { border: { top: ['thin', [7, 0.0]] } },
  { border: { left: ['thin', [7, 0.0]] } },
  { color: [1, 0.0], border: { left: ['thin', [6, 0.0]], right: ['thin', [6, 0.0]], top: ['thin', [6, 0.0]], bottom: ['thin', [6, 0.0]] } },
  { border: { top: ['thin', [6, 0.0]] } },
  { border: { left: ['thin', [6, 0.0]] } },
  { color: [1, 0.0], border: { left: ['thin', [5, 0.0]], right: ['thin', [5, 0.0]], top: ['thin', [5, 0.0]], bottom: ['thin', [5, 0.0]] } },
  { border: { top: ['thin', [5, 0.0]] } },
  { border: { left: ['thin', [5, 0.0]] } },
  { color: [1, 0.0], border: { left: ['thin', [4, 0.0]], right: ['thin', [4, 0.0]], top: ['thin', [4, 0.0]], bottom: ['thin', [4, 0.0]] } },
  { border: { top: ['thin', [4, 0.0]] } },
  { border: { left: ['thin', [4, 0.0]] } },
  { color: [1, 0.0], border: { left: ['thin', [1, 0.0]], right: ['thin', [1, 0.0]], top: ['thin', [1, 0.0]], bottom: ['thin', [1, 0.0]] } },
  { border: { top: ['thin', [1, 0.0]] } },
  { border: { left: ['thin', [1, 0.0]] } },
  { color: [9, -0.25], border: { top: ['thin', [9, 0.0]], bottom: ['thin', [9, 0.0]] } },
  { bold: true, color: [9, -0.25], border: { bottom: ['thin', [9, 0.0]] } },
  { bold: true, color: [9, -0.25], border: { top: ['thin', [9, 0.0]] } },
  { bold: true, color: [9, -0.25] },
  { color: [8, -0.25], border: { top: ['thin', [8, 0.0]], bottom: ['thin', [8, 0.0]] } },
  { bold: true, color: [8, -0.25], border: { bottom: ['thin', [8, 0.0]] } },
  { bold: true, color: [8, -0.25], border: { top: ['thin', [8, 0.0]] } },
  { bold: true, color: [8, -0.25] },
  { color: [7, -0.25], border: { top: ['thin', [7, 0.0]], bottom: ['thin', [7, 0.0]] } },
  { bold: true, color: [7, -0.25], border: { bottom: ['thin', [7, 0.0]] } },
  { bold: true, color: [7, -0.25], border: { top: ['thin', [7, 0.0]] } },
  { bold: true, color: [7, -0.25] },
  { color: [6, -0.25], border: { top: ['thin', [6, 0.0]], bottom: ['thin', [6, 0.0]] } },
  { bold: true, color: [6, -0.25], border: { bottom: ['thin', [6, 0.0]] } },
  { bold: true, color: [6, -0.25], border: { top: ['thin', [6, 0.0]] } },
  { bold: true, color: [6, -0.25] },
  { color: [5, -0.25], border: { top: ['thin', [5, 0.0]], bottom: ['thin', [5, 0.0]] } },
  { bold: true, color: [5, -0.25], border: { bottom: ['thin', [5, 0.0]] } },
  { bold: true, color: [5, -0.25], border: { top: ['thin', [5, 0.0]] } },
  { bold: true, color: [5, -0.25] },
  { color: [4, -0.25], border: { top: ['thin', [4, 0.0]], bottom: ['thin', [4, 0.0]] } },
  { bold: true, color: [4, -0.25], border: { bottom: ['thin', [4, 0.0]] } },
  { bold: true, color: [4, -0.25], border: { top: ['thin', [4, 0.0]] } },
  { bold: true, color: [4, -0.25] },
  { color: [1, 0.0], border: { top: ['thin', [1, 0.0]], bottom: ['thin', [1, 0.0]] } },
  { bold: true, color: [1, 0.0], border: { bottom: ['thin', [1, 0.0]] } },
  { bold: true, color: [1, 0.0], border: { top: ['thin', [1, 0.0]] } },
  { color: [0, 0.0], fill: [9, 0.0] },
  { color: [0, 0.0], fill: [7, 0.0] },
  { color: [0, 0.0], fill: [5, 0.0] },
  { color: [0, 0.0], fill: [1, 0.0] },
  { bold: true, color: [0, 0.0], fill: [1, 0.0], border: { bottom: ['medium', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [9, -0.5], border: { top: ['medium', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [9, -0.25], border: { right: ['medium', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [9, -0.25], border: { left: ['medium', [0, 0.0]] } },
  { fill: [9, -0.25] },
  { color: [0, 0.0], fill: [8, 0.0] },
  { bold: true, color: [0, 0.0], fill: [8, -0.5], border: { top: ['medium', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [8, -0.25], border: { right: ['medium', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [8, -0.25], border: { left: ['medium', [0, 0.0]] } },
  { fill: [8, -0.25] },
  { bold: true, color: [0, 0.0], fill: [7, -0.5], border: { top: ['medium', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [7, -0.25], border: { right: ['medium', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [7, -0.25], border: { left: ['medium', [0, 0.0]] } },
  { fill: [7, -0.25] },
  { color: [0, 0.0], fill: [6, 0.0] },
  { bold: true, color: [0, 0.0], fill: [6, -0.5], border: { top: ['medium', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [6, -0.25], border: { right: ['medium', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [6, -0.25], border: { left: ['medium', [0, 0.0]] } },
  { fill: [6, -0.25] },
  { bold: true, color: [0, 0.0], fill: [5, -0.5], border: { top: ['medium', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [5, -0.25], border: { right: ['medium', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [5, -0.25], border: { left: ['medium', [0, 0.0]] } },
  { fill: [5, -0.25] },
  { color: [0, 0.0], fill: [4, 0.0] },
  { bold: true, color: [0, 0.0], fill: [4, -0.5], border: { top: ['medium', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [4, -0.25], border: { right: ['medium', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [4, -0.25], border: { left: ['medium', [0, 0.0]] } },
  { fill: [4, -0.25] },
  { color: [0, 0.0], fill: [1, 0.45] },
  { bold: true, color: [0, 0.0], fill: [1, 0.15], border: { top: ['medium', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [1, 0.25], border: { right: ['medium', [0, 0.0]] } },
  { bold: true, color: [0, 0.0], fill: [1, 0.25], border: { left: ['medium', [0, 0.0]] } },
  { fill: [1, 0.25] },
];

// prettier-ignore
const STYLES: Readonly<Record<string, Partial<Record<TableStyleElementType, number>>>> = {
  TableStyleLight1: { wholeTable: 140, firstColumnStripe: 26, firstRowStripe: 26, lastColumn: 1, firstColumn: 1, headerRow: 141, totalRow: 142 },
  TableStyleLight2: { wholeTable: 136, firstColumnStripe: 78, firstRowStripe: 78, lastColumn: 139, firstColumn: 139, headerRow: 137, totalRow: 138 },
  TableStyleLight3: { wholeTable: 132, firstColumnStripe: 75, firstRowStripe: 75, lastColumn: 135, firstColumn: 135, headerRow: 133, totalRow: 134 },
  TableStyleLight4: { wholeTable: 128, firstColumnStripe: 72, firstRowStripe: 72, lastColumn: 131, firstColumn: 131, headerRow: 129, totalRow: 130 },
  TableStyleLight5: { wholeTable: 124, firstColumnStripe: 69, firstRowStripe: 69, lastColumn: 127, firstColumn: 127, headerRow: 125, totalRow: 126 },
  TableStyleLight6: { wholeTable: 120, firstColumnStripe: 66, firstRowStripe: 66, lastColumn: 123, firstColumn: 123, headerRow: 121, totalRow: 122 },
  TableStyleLight7: { wholeTable: 116, firstColumnStripe: 63, firstRowStripe: 63, lastColumn: 119, firstColumn: 119, headerRow: 117, totalRow: 118 },
  TableStyleLight8: { wholeTable: 113, firstColumnStripe: 115, secondColumnStripe: 115, firstRowStripe: 114, secondRowStripe: 114, lastColumn: 1, firstColumn: 1, headerRow: 39, totalRow: 80 },
  TableStyleLight9: { wholeTable: 110, firstColumnStripe: 112, secondColumnStripe: 112, firstRowStripe: 111, secondRowStripe: 111, lastColumn: 1, firstColumn: 1, headerRow: 36, totalRow: 77 },
  TableStyleLight10: { wholeTable: 107, firstColumnStripe: 109, secondColumnStripe: 109, firstRowStripe: 108, secondRowStripe: 108, lastColumn: 1, firstColumn: 1, headerRow: 34, totalRow: 74 },
  TableStyleLight11: { wholeTable: 104, firstColumnStripe: 106, secondColumnStripe: 106, firstRowStripe: 105, secondRowStripe: 105, lastColumn: 1, firstColumn: 1, headerRow: 32, totalRow: 71 },
  TableStyleLight12: { wholeTable: 101, firstColumnStripe: 103, secondColumnStripe: 103, firstRowStripe: 102, secondRowStripe: 102, lastColumn: 1, firstColumn: 1, headerRow: 30, totalRow: 68 },
  TableStyleLight13: { wholeTable: 98, firstColumnStripe: 100, secondColumnStripe: 100, firstRowStripe: 99, secondRowStripe: 99, lastColumn: 1, firstColumn: 1, headerRow: 28, totalRow: 65 },
  TableStyleLight14: { wholeTable: 95, firstColumnStripe: 97, secondColumnStripe: 97, firstRowStripe: 96, secondRowStripe: 96, lastColumn: 1, firstColumn: 1, headerRow: 25, totalRow: 62 },
  TableStyleLight15: { wholeTable: 93, firstColumnStripe: 26, firstRowStripe: 26, lastColumn: 1, firstColumn: 1, headerRow: 94, totalRow: 80 },
  TableStyleLight16: { wholeTable: 91, firstColumnStripe: 78, firstRowStripe: 78, lastColumn: 1, firstColumn: 1, headerRow: 92, totalRow: 77 },
  TableStyleLight17: { wholeTable: 89, firstColumnStripe: 75, firstRowStripe: 75, lastColumn: 1, firstColumn: 1, headerRow: 90, totalRow: 74 },
  TableStyleLight18: { wholeTable: 87, firstColumnStripe: 72, firstRowStripe: 72, lastColumn: 1, firstColumn: 1, headerRow: 88, totalRow: 71 },
  TableStyleLight19: { wholeTable: 85, firstColumnStripe: 69, firstRowStripe: 69, lastColumn: 1, firstColumn: 1, headerRow: 86, totalRow: 68 },
  TableStyleLight20: { wholeTable: 83, firstColumnStripe: 66, firstRowStripe: 66, lastColumn: 1, firstColumn: 1, headerRow: 84, totalRow: 65 },
  TableStyleLight21: { wholeTable: 81, firstColumnStripe: 63, firstRowStripe: 63, lastColumn: 1, firstColumn: 1, headerRow: 82, totalRow: 62 },
  TableStyleMedium1: { wholeTable: 79, firstColumnStripe: 26, firstRowStripe: 26, lastColumn: 1, firstColumn: 1, headerRow: 39, totalRow: 80 },
  TableStyleMedium2: { wholeTable: 76, firstColumnStripe: 78, firstRowStripe: 78, lastColumn: 1, firstColumn: 1, headerRow: 36, totalRow: 77 },
  TableStyleMedium3: { wholeTable: 73, firstColumnStripe: 75, firstRowStripe: 75, lastColumn: 1, firstColumn: 1, headerRow: 34, totalRow: 74 },
  TableStyleMedium4: { wholeTable: 70, firstColumnStripe: 72, firstRowStripe: 72, lastColumn: 1, firstColumn: 1, headerRow: 32, totalRow: 71 },
  TableStyleMedium5: { wholeTable: 67, firstColumnStripe: 69, firstRowStripe: 69, lastColumn: 1, firstColumn: 1, headerRow: 30, totalRow: 68 },
  TableStyleMedium6: { wholeTable: 64, firstColumnStripe: 66, firstRowStripe: 66, lastColumn: 1, firstColumn: 1, headerRow: 28, totalRow: 65 },
  TableStyleMedium7: { wholeTable: 61, firstColumnStripe: 63, firstRowStripe: 63, lastColumn: 1, firstColumn: 1, headerRow: 25, totalRow: 62 },
  TableStyleMedium8: { wholeTable: 58, firstColumnStripe: 21, firstRowStripe: 21, lastColumn: 39, firstColumn: 39, headerRow: 59, totalRow: 60 },
  TableStyleMedium9: { wholeTable: 55, firstColumnStripe: 18, firstRowStripe: 18, lastColumn: 36, firstColumn: 36, headerRow: 56, totalRow: 57 },
  TableStyleMedium10: { wholeTable: 52, firstColumnStripe: 15, firstRowStripe: 15, lastColumn: 34, firstColumn: 34, headerRow: 53, totalRow: 54 },
  TableStyleMedium11: { wholeTable: 49, firstColumnStripe: 12, firstRowStripe: 12, lastColumn: 32, firstColumn: 32, headerRow: 50, totalRow: 51 },
  TableStyleMedium12: { wholeTable: 46, firstColumnStripe: 9, firstRowStripe: 9, lastColumn: 30, firstColumn: 30, headerRow: 47, totalRow: 48 },
  TableStyleMedium13: { wholeTable: 43, firstColumnStripe: 6, firstRowStripe: 6, lastColumn: 28, firstColumn: 28, headerRow: 44, totalRow: 45 },
  TableStyleMedium14: { wholeTable: 40, firstColumnStripe: 3, firstRowStripe: 3, lastColumn: 25, firstColumn: 25, headerRow: 41, totalRow: 42 },
  TableStyleMedium15: { wholeTable: 37, firstColumnStripe: 26, firstRowStripe: 26, lastColumn: 39, firstColumn: 39, headerRow: 38, totalRow: 24 },
  TableStyleMedium16: { wholeTable: 22, firstColumnStripe: 26, firstRowStripe: 26, lastColumn: 36, firstColumn: 36, headerRow: 35, totalRow: 24 },
  TableStyleMedium17: { wholeTable: 22, firstColumnStripe: 26, firstRowStripe: 26, lastColumn: 34, firstColumn: 34, headerRow: 33, totalRow: 24 },
  TableStyleMedium18: { wholeTable: 22, firstColumnStripe: 26, firstRowStripe: 26, lastColumn: 32, firstColumn: 32, headerRow: 31, totalRow: 24 },
  TableStyleMedium19: { wholeTable: 22, firstColumnStripe: 26, firstRowStripe: 26, lastColumn: 30, firstColumn: 30, headerRow: 29, totalRow: 24 },
  TableStyleMedium20: { wholeTable: 22, firstColumnStripe: 26, firstRowStripe: 26, lastColumn: 28, firstColumn: 28, headerRow: 27, totalRow: 24 },
  TableStyleMedium21: { wholeTable: 22, firstColumnStripe: 26, firstRowStripe: 26, lastColumn: 25, firstColumn: 25, headerRow: 23, totalRow: 24 },
  TableStyleMedium22: { wholeTable: 19, firstColumnStripe: 21, firstRowStripe: 21, lastColumn: 1, firstColumn: 1, headerRow: 1, totalRow: 20 },
  TableStyleMedium23: { wholeTable: 16, firstColumnStripe: 18, firstRowStripe: 18, lastColumn: 1, firstColumn: 1, headerRow: 1, totalRow: 17 },
  TableStyleMedium24: { wholeTable: 13, firstColumnStripe: 15, firstRowStripe: 15, lastColumn: 1, firstColumn: 1, headerRow: 1, totalRow: 14 },
  TableStyleMedium25: { wholeTable: 10, firstColumnStripe: 12, firstRowStripe: 12, lastColumn: 1, firstColumn: 1, headerRow: 1, totalRow: 11 },
  TableStyleMedium26: { wholeTable: 7, firstColumnStripe: 9, firstRowStripe: 9, lastColumn: 1, firstColumn: 1, headerRow: 1, totalRow: 8 },
  TableStyleMedium27: { wholeTable: 4, firstColumnStripe: 6, firstRowStripe: 6, lastColumn: 1, firstColumn: 1, headerRow: 1, totalRow: 5 },
  TableStyleMedium28: { wholeTable: 0, firstColumnStripe: 3, firstRowStripe: 3, lastColumn: 1, firstColumn: 1, headerRow: 1, totalRow: 2 },
  TableStyleDark1: { wholeTable: 175, firstColumnStripe: 179, firstRowStripe: 179, lastColumn: 178, firstColumn: 177, headerRow: 147, totalRow: 176 },
  TableStyleDark2: { wholeTable: 170, firstColumnStripe: 174, firstRowStripe: 174, lastColumn: 173, firstColumn: 172, headerRow: 147, totalRow: 171 },
  TableStyleDark3: { wholeTable: 145, firstColumnStripe: 169, firstRowStripe: 169, lastColumn: 168, firstColumn: 167, headerRow: 147, totalRow: 166 },
  TableStyleDark4: { wholeTable: 161, firstColumnStripe: 165, firstRowStripe: 165, lastColumn: 164, firstColumn: 163, headerRow: 147, totalRow: 162 },
  TableStyleDark5: { wholeTable: 144, firstColumnStripe: 160, firstRowStripe: 160, lastColumn: 159, firstColumn: 158, headerRow: 147, totalRow: 157 },
  TableStyleDark6: { wholeTable: 152, firstColumnStripe: 156, firstRowStripe: 156, lastColumn: 155, firstColumn: 154, headerRow: 147, totalRow: 153 },
  TableStyleDark7: { wholeTable: 143, firstColumnStripe: 151, firstRowStripe: 151, lastColumn: 150, firstColumn: 149, headerRow: 147, totalRow: 148 },
  TableStyleDark8: { wholeTable: 26, firstColumnStripe: 21, firstRowStripe: 21, lastColumn: 1, firstColumn: 1, headerRow: 146, totalRow: 80 },
  TableStyleDark9: { wholeTable: 78, firstColumnStripe: 18, firstRowStripe: 18, lastColumn: 1, firstColumn: 1, headerRow: 145, totalRow: 80 },
  TableStyleDark10: { wholeTable: 72, firstColumnStripe: 12, firstRowStripe: 12, lastColumn: 1, firstColumn: 1, headerRow: 144, totalRow: 80 },
  TableStyleDark11: { wholeTable: 66, firstColumnStripe: 6, firstRowStripe: 6, lastColumn: 1, firstColumn: 1, headerRow: 143, totalRow: 80 },
};

/**
 * A built-in table style by its name, each region with its format.
 *
 * @param name The style's name as a workbook gives it (`TableStyleMedium2`).
 * @returns Its regions' formats, or undefined for a name Excel does not build in.
 */
export function presetTableStyle(
  name: string,
): Partial<Record<TableStyleElementType, PresetDxf>> | undefined {
  const style = STYLES[name];
  if (!style) return undefined;
  const out: Partial<Record<TableStyleElementType, PresetDxf>> = {};
  for (const [type, i] of Object.entries(style)) {
    out[type as TableStyleElementType] = DXFS[i]!;
  }
  return out;
}
