// Generate `src/pdf-reader/standard-metrics.ts` from Adobe's Core 14 AFM files.
//
// ISO 32000-1 §9.6.2.2 — the 14 standard Type 1 fonts need not be embedded and
// need not carry a `/Widths` array, because "a conforming reader shall have
// built-in font metrics for them". Those metrics are Adobe's own AFM files,
// which Adobe published for exactly this purpose and which ship with
// Ghostscript, matplotlib, TeX distributions and most PDF libraries.
//
// This script does not fetch them: point it at a directory that has them.
//
//   npx tsx scripts/build-standard-metrics.ts /path/to/pdfcorefonts
//
// Four of the fourteen are metrically identical to another four (an oblique is
// the upright slanted, not respaced), and all four Couriers are 600 flat, so
// eight tables cover all of them. Each is emitted as a single string of
// `name code width` triples — the glyph's own name, the code Adobe's built-in
// encoding gives it, and its advance in 1000ths of an em.

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

/** The faces that carry their own table; the rest resolve onto one of these. */
const FACES = [
  'Helvetica',
  'Helvetica-Bold',
  'Times-Roman',
  'Times-Bold',
  'Times-Italic',
  'Times-BoldItalic',
  'Symbol',
  'ZapfDingbats',
] as const;

function tripleString(afm: string): string {
  const out: Array<string> = [];
  for (const line of afm.split('\n')) {
    const m = /^C\s+(-?\d+)\s*;\s*WX\s+(-?\d+)\s*;\s*N\s+(\S+)\s*;/u.exec(line);
    if (!m) continue;
    out.push(`${m[3]!} ${m[1]!} ${m[2]!}`);
  }
  return out.join(' ');
}

function main(): void {
  const dir = process.argv[2];
  if (dir === undefined) throw new Error('usage: build-standard-metrics.ts <afm-directory>');
  const tables = FACES.map((face) => {
    const afm = readFileSync(resolve(dir, `${face}.afm`), 'latin1');
    const notice = /^Comment (Copyright.*)$/mu.exec(afm)?.[1] ?? '';
    return { face, triples: tripleString(afm), notice };
  });
  const notice = tables[0]?.notice ?? '';
  const body = [
    '// ISO 32000-1 §9.6.2.2 — the built-in metrics of the 14 standard Type 1',
    '// fonts, which need not be embedded and need not carry a `/Widths` array',
    '// because "a conforming reader shall have built-in font metrics for them".',
    '//',
    '// GENERATED by `scripts/build-standard-metrics.ts` from the Adobe Font',
    '// Metrics files Adobe published for this purpose. Do not edit by hand: fix',
    '// the script and run it again.',
    '//',
    `// ${notice}`,
    '',
    '/**',
    " * One face's metrics: `name code width` triples, where the name is the",
    " * glyph's own, the code is the one Adobe's built-in encoding gives it, and",
    ' * the width is its advance in 1000ths of an em.',
    ' */',
    'export const STANDARD_METRICS: Readonly<Record<string, string>> = {',
    // Unquoted where the name is a plain identifier, which is what Prettier
    // leaves behind: the file is checked by `format:check` like any other.
    ...tables.map(
      (t) => `  ${/^[A-Za-z][\w]*$/u.test(t.face) ? t.face : `'${t.face}'`}:\n    '${t.triples}',`,
    ),
    '};',
    '',
    '/** Every Courier is 600 wide, every glyph — it is a typewriter face. */',
    'export const COURIER_WIDTH = 600;',
    '',
  ].join('\n');
  const out = resolve('src/pdf-reader/standard-metrics.ts');
  writeFileSync(out, body);
  process.stdout.write(
    `${out}: ${String(tables.length)} faces, ${String(Math.round(body.length / 1024))}KB\n`,
  );
}

main();
